
# Syntax highlighting
markdown:             kramdown
mathjax:              true
highlighter:          rouge

# Permalinks
permalink:           /:title/

# Setup
timezone:            Europe/Paris # eg. Asia/Kathmandu
locale:              fr_FR # eg. en_us
name:				         Make it Shaded
title:               Make it Shaded
tagline:
description:         Make it Shaded
url:
rss:
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                 # /assets/img/icon.png [best 300px X 300px]
disqus:               # get it on https://disqus.com/admin/

authors:
  Axel:
    id:                Axel
    name:              Axel Paris
    avatar:            '/assets/images/axel.jpg'
    twitter:           https://twitter.com/Axel_Paris
    email:             axel.paris69@gmail.com
    github:            Moon519
    site:              moon519.github.io/index.html

  hrkz:
    id:                hrkz
    name:              Hugo Frezat
    avatar:            '/assets/images/hrkz.jpg'
    bio:               Physics enthusiast & student in applied maths/computer science.
    twitter:           https://twitter.com/hrkz____
    github:            hrkz

  Razakhel:
    id:                Razakhel
    name:              Romain Milbert
    gravatar:          6037026c1ca3ba8fcaccc30f214da703
    bio:               Master's degree student in Computer Graphics; specialized in real-time & raytraced rendering, and a bit of image analysis.
    email:             romain.milbert@gmail.com
    linkedin:          https://www.linkedin.com/in/romainmilbert/
    github:            Razakhel

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
